### ISSUE TITLE
Benchmarks have only half the relations reported

### ISSUE THREAD

**Issue by nomisto** [migalkin/ilpc2022#10]
Hi, I can be wrong but I recalculated the number of relations of the benchmarks. For the large variant I get 65 relations and for the small I get only 48, which is exactly half the relations reported in your table. Maybe this is because nodepiece needs inverse relations explicitly?

**Comment by migalkin** [comment]
Yes, the paper reports a doubled number of relations that includes inverse edge types

**Comment by nomisto** [comment]
Thanks!
